#!/usr/bin/env node
/**
 * SessionStart hook for Hermes.
 * 1. Regenerates .workspace/codex/ index files
 * 2. Generates optimized agent context brief
 * 3. Detects repeated prompts and auto-extracts them into skills
 * 4. Injects a context summary into the session
 */

'use strict';

const { execSync } = require('child_process');
const fs   = require('fs');
const path = require('path');

const ROOT       = process.cwd();
const SKILLS_DIR = path.join(ROOT, '.claude', 'skills');
const LOG_PATH   = path.join(ROOT, '.claude', 'prompt-log.jsonl');

// ── 1. Regenerate codex index ─────────────────────────────────────────────────
let codexStatus = '';
try {
  execSync('node tools/generate-codex.js', { cwd: ROOT, stdio: 'pipe', timeout: 15000 });
  codexStatus = 'refreshed';
} catch (e) {
  codexStatus = 'skipped (error: ' + (e.message || '').split('\n')[0] + ')';
}

// ── 2. Generate optimized agent context brief ─────────────────────────────────
let optimizedStatus = '';
try {
  execSync(
    'node tools/optimize-agent-context.mjs --agent claude --tasks TASKS.md --guide CLAUDE.md --queue-mode first --write',
    { cwd: ROOT, stdio: 'pipe', timeout: 15000 }
  );
  optimizedStatus = 'ready — read .workspace/codex/optimized-claude.md for queue status before rereading TASKS.md';
} catch {
  optimizedStatus = 'skipped — read TASKS.md directly';
}

// ── 3. Detect repeated prompts and auto-extract skills ────────────────────────
const REPEAT_THRESHOLD = 3;

// Stop-words to skip when building a skill slug
const STOP = new Set([
  'follow', 'read', 'run', 'the', 'and', 'or', 'a', 'an', 'to', 'in',
  'for', 'of', 'with', 'on', 'at', 'by', 'from', 'this', 'that', 'is',
  'are', 'be', 'do', 'not', 'if', 'it', 'my', 'we', 'you', 'me', 'no',
  'so', 'up', 'as', 'all', 'any', 'can', 'has', 'had', 'was', 'but',
  'get', 'got', 'let', 'set', 'use', 'make', 'take', 'add', 'put', 'see',
  'how', 'what', 'when', 'where', 'which', 'who', 'will', 'just', 'now',
  'then', 'there', 'their', 'they', 'them', 'every', 'each', 'after',
  'before', 'into', 'also', 'should', 'must', 'only', 'once', 'done',
  'using', 'mode', 'task', 'tasks', 'step', 'steps', 'new', 'next',
  'please', 'always', 'never', 'else', 'other', 'more', 'less',
]);

function slugify(text) {
  const words = text
    .toLowerCase()
    .replace(/[^\w\s]/g, ' ')
    .split(/\s+/)
    .filter(w => w.length > 2 && !STOP.has(w));
  return words.slice(0, 4).join('-') || 'auto-skill';
}

const autoSkillsCreated = [];

try {
  if (fs.existsSync(LOG_PATH)) {
    const lines = fs.readFileSync(LOG_PATH, 'utf-8').trim().split('\n').filter(Boolean);

    // Count occurrences per hash; keep first sample text
    const counts  = {};
    const samples = {};
    for (const line of lines) {
      try {
        const { hash, text } = JSON.parse(line);
        counts[hash]  = (counts[hash]  || 0) + 1;
        if (!samples[hash]) samples[hash] = text;
      } catch { /* malformed line — skip */ }
    }

    for (const [hash, count] of Object.entries(counts)) {
      if (count < REPEAT_THRESHOLD) continue;

      const text      = samples[hash];
      const slug      = slugify(text);
      const skillDir  = path.join(SKILLS_DIR, slug);
      const skillFile = path.join(skillDir, 'SKILL.md');

      // Only create if no skill with this slug exists yet
      if (!fs.existsSync(skillFile)) {
        fs.mkdirSync(skillDir, { recursive: true });

        const skill = [
          '---',
          `name: ${slug}`,
          `description: Auto-extracted from a prompt repeated ${count} times. Review and refine the body.`,
          'user-invocable: true',
          '---',
          '',
          '<!-- Auto-generated by session-start from a repeated prompt. -->',
          '<!-- Review the body below and refine it into a proper skill. -->',
          '',
          text,
        ].join('\n');

        fs.writeFileSync(skillFile, skill, 'utf-8');
        autoSkillsCreated.push({ slug, count, preview: text.slice(0, 100) });
      }
    }
  }
} catch { /* non-fatal — never block session start */ }

// ── 4. Build additionalContext ────────────────────────────────────────────────
const skillNotice = autoSkillsCreated.length
  ? '\n\n### Auto-extracted skills (from repeated prompts)\n' +
    autoSkillsCreated
      .map(s => `- /${s.slug} (seen ${s.count}×): "${s.preview}…"\n  File: .claude/skills/${s.slug}/SKILL.md — review and refine the body`)
      .join('\n')
  : '';

const context = `
## Hermes Session Tools (auto-loaded)

### Codebase Index (.workspace/codex/) — ${codexStatus}
Full structured index available. Reference these files before scanning source:
- .workspace/codex/routes.md     — Spring Boot REST endpoints
- .workspace/codex/pages.md      — React pages + feature tags
- .workspace/codex/lib.md        — Frontend utility exports
- .workspace/codex/schema.md     — JPA entities + relations
- .workspace/codex/components.md — React components + props

Regenerate after structural changes: node tools/generate-codex.js

### Optimized context brief — ${optimizedStatus}

### Loop mode shortcut
To run the task queue, say: /loop-mode
This is equivalent to the full loop invocation prompt — no need to type it manually.
${skillNotice}
`.trim();

// ── 5. Output JSON for Claude ─────────────────────────────────────────────────
process.stdout.write(JSON.stringify({
  hookSpecificOutput: {
    hookEventName: 'SessionStart',
    additionalContext: context,
  },
}) + '\n');
