/**
 * HermesRuns symbol: the H with a road cut under its crossbar (same drawing as /hermes-tab-icon.svg).
 * Generated by replica/tools/brand_logo.py; change the drawing there, not here.
 * @param {'light'|'dark'} tone - light: navy tile (the default, on light and dark UI); dark: white tile.
 */
const TILE = 'M22 0H78A22 22 0 0 1 100 22V78A22 22 0 0 1 78 100H22A22 22 0 0 1 0 78V22A22 22 0 0 1 22 0Z';
const LETTER = 'M20 80V30L37 20V44H63V30L80 20V80H63L55 56H45L37 80Z';
const ROAD = 'M49 58H51L51.15 61H48.85ZM48.7 63H51.3L51.6 68H48.4ZM48.3 71H51.7L52.3 79.5H47.7Z';

export default function HermesMarkSvg({ tone = 'light', className = '' }) {
  const tile = tone === 'dark' ? '#ffffff' : '#10203d';
  const letter = tone === 'dark' ? '#10203d' : '#ffffff';
  const road = tone === 'dark' ? '#a0392a' : '#f07561';

  return (
    <svg
      className={className}
      viewBox="0 0 100 100"
      width="32"
      height="32"
      aria-hidden="true"
      focusable="false"
    >
      <path fill={tile} d={TILE} />
      <path fill={letter} d={LETTER} />
      <path fill={road} d={ROAD} />
    </svg>
  );
}
