/**
 * HermesRuns logotype, "hermesruns": custom geometric lowercase, drawn as strokes so it renders the same on
 * every system (no font needed). Generated by replica/tools/brand_logo.py; change the drawing there.
 * "hermes" uses currentColor; "runs" uses --hermes-logo-accent (brick on light, coral on dark) and falls back
 * to currentColor, which gives the one-colour logotype. Its box is the ascender to the baseline, so set its
 * height to the symbol's height when they sit together.
 */
const INK = 'M12 38.5A28 28 0 0 1 68 38.5V100M114 50H193A39.5 39.5 0 1 0 185.46 73.22M239 0V100M239 38.5A28 28 0 0 1 267 10.5H281M302 0V100M302 32.5A22 22 0 0 1 346 32.5V100M346 32.5A22 22 0 0 1 390 32.5V100M436 50H515A39.5 39.5 0 1 0 507.46 73.22M593.85 20.38A19.75 19.75 0 1 0 576.75 50A19.75 19.75 0 1 1 559.65 79.62';
const H_STEM = 'M0 100V-30L24 -44V100Z';
const ACCENT = 'M642.5 0V100M642.5 38.5A28 28 0 0 1 670.5 10.5H684.5M705.5 0V61.5A28 28 0 0 0 761.5 61.5M761.5 0V100M812.5 0V100M812.5 38.5A28 28 0 0 1 868.5 38.5V100M951.35 20.38A19.75 19.75 0 1 0 934.25 50A19.75 19.75 0 1 1 917.15 79.62';

export default function HermesWordmarkSvg({ className = '', title = 'HermesRuns' }) {
  return (
    <svg
      className={`hermes-wordmark${className ? ` ${className}` : ''}`}
      viewBox="0 -44 966 144"
      role="img"
      aria-label={title}
      focusable="false"
    >
      <path fill="none" stroke="currentColor" strokeWidth="24" d={INK} />
      <path fill="currentColor" d={H_STEM} />
      <path fill="none" strokeWidth="24" style={{ stroke: 'var(--hermes-logo-accent, currentColor)' }} d={ACCENT} />
    </svg>
  );
}
