import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
const layout = readFileSync(new URL('./SettingsAtlasLayout.jsx', import.meta.url), 'utf8');
const styles = readFileSync(new URL('../styles/settings-v2.css', import.meta.url), 'utf8');
assert.match(layout, /className=\{stravaConnected \? 'st-v2-btn' : 'st-v2-btn is-dark'\}/, 'Strava should use a compact action with a distinct connect state.');
assert.match(layout, /onClick=\{stravaConnected \? disconnectStrava : connectStrava\}/, 'Strava should keep its existing connection actions.');
assert.match(layout, /onClick=\{onOpenGarminImport\}/, 'Garmin should retain the import modal entry.');
assert.match(styles, /\.st-v2-row\s*\{[^}]*grid-template-columns:\s*minmax\(0, 1fr\) auto/, 'Actions should share a row with readable provider copy.');
assert.match(styles, /\.st-v2-btn\s*\{[^}]*display:\s*inline-grid;[^}]*min-height:\s*34px/, 'Desktop buttons should stay compact.');
assert.match(styles, /@media \(max-width: 640px\)[\s\S]*?min-height:\s*44px/, 'Mobile actions should retain comfortable touch targets.');
assert.match(styles, /\.st-v2-row-copy > span\s*\{[^}]*overflow-wrap:\s*anywhere/, 'Long provider summaries should wrap inside the row.');
console.log('[PASS] Settings connection row actions passed.');
