package com.hermes.backend;

import com.fasterxml.jackson.annotation.JsonIgnore;
import jakarta.persistence.*;

@Entity
@Table(
        name = "activity_points",
        indexes = {
                @Index(name = "idx_activity_point_activity", columnList = "activity_id"),
                @Index(name = "idx_activity_point_activity_sequence", columnList = "activity_id, sequenceIndex")
        }
)
public class ActivityPoint {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "activity_id", nullable = false)
    private Activity activity;

    private int sequenceIndex;

    private double latitude;

    private double longitude;

    /** Elapsed seconds from activity start for this sample (if available). */
    private Integer elapsedSeconds;

    /** Cumulative distance from start in meters for this sample (if available). */
    private Double distanceMeters;

    /** Elevation / altitude in meters for this sample (if available). */
    private Double elevationMeters;

    /** Immutable raw elevation exactly as provided by source watch/file stream. */
    private Double elevationRawMeters;

    /** Nullable corrected elevation generated by DEM recalibration. */
    private Double elevationCorrectedMeters;

    /** Heart rate for this sample in bpm (if available). */
    private Integer heartRate;

    /** Cadence for this sample in steps per minute (if available). */
    private Integer cadence;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @JsonIgnore
    public Activity getActivity() {
        return activity;
    }

    public void setActivity(Activity activity) {
        this.activity = activity;
    }

    public int getSequenceIndex() {
        return sequenceIndex;
    }

    public void setSequenceIndex(int sequenceIndex) {
        this.sequenceIndex = sequenceIndex;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public Integer getElapsedSeconds() {
        return elapsedSeconds;
    }

    public void setElapsedSeconds(Integer elapsedSeconds) {
        this.elapsedSeconds = elapsedSeconds;
    }

    public Double getDistanceMeters() {
        return distanceMeters;
    }

    public void setDistanceMeters(Double distanceMeters) {
        this.distanceMeters = distanceMeters;
    }

    public Double getElevationMeters() {
        return elevationMeters;
    }

    public void setElevationMeters(Double elevationMeters) {
        this.elevationMeters = elevationMeters;
    }

    public Double getElevationRawMeters() {
        return elevationRawMeters;
    }

    public void setElevationRawMeters(Double elevationRawMeters) {
        this.elevationRawMeters = elevationRawMeters;
    }

    public Double getElevationCorrectedMeters() {
        return elevationCorrectedMeters;
    }

    public void setElevationCorrectedMeters(Double elevationCorrectedMeters) {
        this.elevationCorrectedMeters = elevationCorrectedMeters;
    }

    public Integer getHeartRate() {
        return heartRate;
    }

    public void setHeartRate(Integer heartRate) {
        this.heartRate = heartRate;
    }

    public Integer getCadence() {
        return cadence;
    }

    public void setCadence(Integer cadence) {
        this.cadence = cadence;
    }
}
