#!/usr/bin/env bash
# Untrack auto-generated .ai-sync state files that are regenerated on every loop run.
# Safe: only removes from git index; files stay on disk. Reversible via git restore --staged.
#
# Run from repo root. Review `git status` after, then commit:
#   ./.tools/untrack-volatile-ai-sync.sh
#   git status
#   git commit -m "chore(ai-sync): untrack auto-generated coordinator/controller/loop state"
#
# Files KEPT tracked (cross-agent coordination layer that humans + agents read):
#   HUMAN_LOOP.md, AGENT_SYNC.{md,json}, CONTEXT_LEDGER.md, TEAMWORK.md
#
# Files UN-tracked (regenerated by --write on every loop refresh):
set -e
patterns=(
  ".ai-sync/AUTO_HERMES_CONTROLLER.*"
  ".ai-sync/AUTO_HERMES_COORDINATOR.*"
  ".ai-sync/AUTO_HERMES_LOOP*.*"
  ".ai-sync/AUTO_HERMES_FINISH.*"
  ".ai-sync/AUTO_HERMES_PROMOTION.*"
  ".ai-sync/AUTO_HERMES_ROUND_RESULT.*"
  ".ai-sync/AUTO_HERMES_SELF_*.*"
  ".ai-sync/AUTO_HERMES_MAX*.*"
  ".ai-sync/AUTO_HERMES_TELEMETRY.*"
  ".ai-sync/AUTO_HERMES_DOCKER_GATE.*"
  ".ai-sync/AUTO_HERMES_HEALTH_CHECK.*"
  ".ai-sync/AUTO_HERMES_NEXT_PROMPT.*"
  ".ai-sync/AUTO_HERMES_TRACE_TO_SKILL.*"
  ".ai-sync/AUTO_HERMES_NOTIFY.*"
  ".ai-sync/AUTO_HERMES_PULL_MAIN.*"
  ".ai-sync/AUTO_HERMES_SUBAGENT_CATALOG.*"
  ".ai-sync/auto-hermes-state/"
  ".ai-sync/auto-hermes-max-state/"
  ".ai-sync/auto-hermes-max-lanes/"
  ".ai-sync/auto-hermes-max-results/"
  ".ai-sync/context-snapshots/"
  ".ai-sync/LOCAL_CONSOLE_ERRORS.*"
  ".ai-sync/LOOP_STATE.md"
  ".ai-sync/OMX_AUTO_HERMES_BRIDGE.*"
  ".ai-sync/QUALITY_AUDIT.md"
  ".ai-sync/SELF_EVOLVING_AUDIT.md"
  ".ai-sync/RUNAWAY_COUNTER.json"
  ".ai-sync/error.md"
)
total=0
for p in "${patterns[@]}"; do
  count=$(git ls-files "$p" | wc -l)
  if [ "$count" -gt 0 ]; then
    echo "Untracking $count files matching $p"
    git rm -r --cached --quiet "$p" 2>/dev/null || true
    total=$((total + count))
  fi
done
echo ""
echo "Untracked $total files total. They remain on disk."
echo "Review with: git status --short | head -40"
echo "Commit with: git commit -m 'chore(ai-sync): untrack auto-generated state files'"
