import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { spawnSync } from 'node:child_process';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { test } from 'node:test';
import {
  buildLandMask, createLandTest, decodeLandRuns, decodeTopologyRings, encodeLandRuns, fibonacciPoint, landBandOrder, maskHasPoint,
  renderLandModule, validateLandMask, VALIDATION_POINTS,
} from './generate-landing-globe-land.mjs';

const repositoryRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const generator = path.join(repositoryRoot, 'tools/generate-landing-globe-land.mjs');
const committed = path.join(repositoryRoot, 'frontend/src/data/landingGlobeLand.js');

// Quantized TopoJSON: 0.1° per step from -180/-90. Arc 0 is a 0..10° square,
// arc 1 crosses the antimeridian, arc 2 rings the south pole at -70°.
const toQuantized = (points) => points.map(([lng, lat]) => [Math.round((lng + 180) * 10), Math.round((lat + 90) * 10)])
  .map((point, index, all) => (index === 0 ? point : [point[0] - all[index - 1][0], point[1] - all[index - 1][1]]));
const polarRing = Array.from({ length: 37 }, (_, index) => [index === 36 ? -180 : -180 + index * 10, -70]).reverse();
const topology = {
  type: 'Topology',
  transform: { scale: [0.1, 0.1], translate: [-180, -90] },
  objects: { land: { type: 'GeometryCollection', geometries: [
    { type: 'Polygon', arcs: [[0]] },
    { type: 'MultiPolygon', arcs: [[[1]], [[2]]] },
  ] } },
  arcs: [
    toQuantized([[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]]),
    toQuantized([[170, 60], [180, 60], [-170, 60], [-170, 70], [180, 70], [170, 70], [170, 60]]),
    toQuantized([...polarRing, polarRing[0]]),
  ],
};

test('decodes quantized TopoJSON rings and tests land with antimeridian and polar rings', () => {
  const rings = decodeTopologyRings(topology);
  assert.equal(rings.length, 3);
  assert.deepEqual(rings[0].map(([lng, lat]) => [Math.round(lng), Math.round(lat)]), [[0, 0], [10, 0], [10, 10], [0, 10], [0, 0]]);
  const isLand = createLandTest(rings);
  assert.equal(isLand(5, 5), true);
  assert.equal(isLand(5, 15), false);
  assert.equal(isLand(65, 175), true);
  assert.equal(isLand(65, -175), true);
  assert.equal(isLand(65, 0), false, 'An antimeridian ring must not smear across the whole map.');
  assert.equal(isLand(-85, 30), true, 'A ring around the pole closes through the pole.');
  assert.equal(isLand(-60, 30), false);
});

test('keeps the Fibonacci lattice and the run order identical to the frontend decoder', async () => {
  const frontend = await import(pathToFileURL(path.join(repositoryRoot, 'frontend/src/utils/landingGlobe.js')).href);
  for (const index of [0, 1, 777, 12345, 59999]) assert.deepEqual(fibonacciPoint(index, 60000), frontend.fibonacciPoint(index, 60000));
  for (const count of [1000, 20000, 60000]) assert.deepEqual([...landBandOrder(count)], [...frontend.landBandOrder(count)]);
});

test('encodes the land flags as band-ordered run lengths in a generated module', async () => {
  const { bytes, land } = buildLandMask((lat) => lat > 0, 1000);
  assert.equal(land, 500);
  assert.equal(maskHasPoint(bytes, 0), true);
  assert.equal(maskHasPoint(bytes, 999), false);
  const patchy = buildLandMask((lat, lng) => Math.sin(lat / 7) * Math.cos(lng / 11) > 0.2, 5000).bytes;
  assert.deepEqual([...decodeLandRuns(encodeLandRuns(patchy, 5000), 5000)], [...patchy]);
  const source = renderLandModule(bytes, 1000);
  assert.match(source, /^\/\/ GENERATED by tools\/generate-landing-globe-land\.mjs — do not edit\./);
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'globe-land-'));
  try {
    const file = path.join(directory, 'mask.mjs');
    fs.writeFileSync(file, source);
    const module = await import(pathToFileURL(file).href);
    assert.equal(module.LANDING_GLOBE_POINT_COUNT, 1000);
    assert.deepEqual([...decodeLandRuns(module.LANDING_GLOBE_LAND_RUNS, 1000)], [...bytes]);
    const frontend = await import(pathToFileURL(path.join(repositoryRoot, 'frontend/src/utils/landingGlobe.js')).href);
    const flags = frontend.decodeLandRuns(module.LANDING_GLOBE_LAND_RUNS, 1000);
    assert.deepEqual([...flags].map((flag, index) => Boolean(flag) === maskHasPoint(bytes, index)), Array(1000).fill(true));
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});

test('the committed land mask is compact, attributed and passes the known-point checks', async () => {
  const source = fs.readFileSync(committed, 'utf8');
  assert.ok(Buffer.byteLength(source) < 5 * 1024, 'landingGlobeLand.js should stay below 5 KiB.');
  assert.match(source, /^\/\/ GENERATED by tools\/generate-landing-globe-land\.mjs — do not edit\./);
  assert.match(source, /Natural Earth 1:110m land \(public domain\) via world-atlas@2/);
  const { LANDING_GLOBE_POINT_COUNT: count, LANDING_GLOBE_LAND_RUNS: runs } = await import(pathToFileURL(committed).href);
  assert.ok(count >= 40000 && count <= 80000, 'The dense lattice keeps coastlines legible when the globe is zoomed in.');
  const bytes = decodeLandRuns(runs, count);
  assert.equal(bytes.length, Math.ceil(count / 8));
  assert.deepEqual(validateLandMask(bytes, count), []);
  assert.ok(VALIDATION_POINTS.some(([, , , land]) => land) && VALIDATION_POINTS.some(([, , , land]) => !land));
});

test('the CLI refuses to write an unvalidated mask and reports usage errors', () => {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'globe-land-cli-'));
  try {
    const input = path.join(directory, 'land.json');
    const out = path.join(directory, 'land.js');
    fs.writeFileSync(input, JSON.stringify(topology));
    const usage = spawnSync(process.execPath, [generator], { encoding: 'utf8' });
    assert.equal(usage.status, 1);
    assert.match(usage.stderr, /Usage:/);
    // The synthetic topology has no continents, so the known-point validation must refuse to write.
    const rejected = spawnSync(process.execPath, [generator, input, '--points', '2000', '--out', out], { encoding: 'utf8' });
    assert.equal(rejected.status, 1);
    assert.match(rejected.stderr, /validation failed: Berlin should be land/);
    assert.equal(fs.existsSync(out), false);
  } finally {
    fs.rmSync(directory, { recursive: true, force: true });
  }
});
